### PR TITLE
Java Compatibility

### PR DESCRIPTION
**Pull request by bernard-wagner**
Added compatibility for build process for Java 7/8.

Prevents bad magic number exception from dx when building.

### CODE REVIEW

**Comment by HenryHoggard** [comment]
I don't think we want to be forcing it to use java 6. Instead it should use whichever version they have set as their default, or in their .drozer_config file. Is there any particular reason why we need to force it onto Java 1.6?

**Comment by anantshri** [comment]
as of right now current source specifically works only with java 8 may be this patch can help us in compiling this with java 7. Make apks fail with incompatible verision eror.

Error attached below.

```
make apks
cd src/drozer/modules/common/; javac -cp /vagrant/Build/drozer/source/src/drozer/lib/android.jar ByteStreamReader.java
cd src/drozer/modules/common/; dx --dex --output=ByteStreamReader.apk ByteStreamReader*.class
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/dx/command/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
Makefile:37: recipe for target 'src/drozer/modules/common/ByteStreamReader.apk' failed
make: *** [src/drozer/modules/common/ByteStreamReader.apk] Error 1
rm src/drozer/modules/common/ByteStreamReader.class
```

changing java to 8 allows us to run make apks sucessfully. 

Can someone comment on this please.

**Comment by HenryHoggard** [comment]
Hi @anantshri. Java 7 works for me, if you are having problems can you create a separate issue and I will  look into it.

**Comment by anantshri** [comment]
@HenryHoggard dig a bit further its a bit strange bug raised https://github.com/mwrlabs/drozer/issues/258

**Pull request closed without merging**
